language: R
cache: packages
dist: trusty
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - unixodbc
    - unixodbc-dev
    - tdsodbc
    - libsqliteodbc

script:
- make travis
