---
title: "Defining Non-Traditional Students"
author: "Alex Axthelm"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: zenburn
    theme: readable
    toc: yes
    toc_float: yes
  flexdashboard::flex_dashboard:
    orientation: columns
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---

```{r setup_variables, include = FALSE, cache = FALSE}
is_draft <- TRUE

use_live_sql <- if (identical(Sys.getenv("CONTINUOUS_INTEGRATION"), "true")){
  FALSE
} else {
  !(dir.exists("data") & is_draft)
}
show_sql_code <- (use_live_sql & is_draft)

set.seed(20170419)
ptm <- proc.time()[3]
project_sql_server <- "CHESQLP01VW"
excel_list <- list()
```

```{r load_packages, cache = FALSE, message = FALSE, echo = FALSE, include = FALSE}
library(knitr)
library(DT)
library(plotly)
library(tidyverse)
library(DBI)
library(htmltools)
library(broom)
library(openxlsx)
if (use_live_sql) {library(odbc)}
library(RSQLite)
library(openssl)
library(git2r)
library(sodium)
library(IndianaCHEmisc)
library(readr)
```

```{r set_knitr_options, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(
  cache = FALSE,
  message = is_draft,
  warning = is_draft,
  autodep = TRUE
  )
```

```{r git_info, include = is_draft, cache = FALSE}
if (Sys.getenv("CONTINUOUS_INTEGRATION") == "true") {
  git_info <- NULL
} else {
  git_info <- as(git2r::lookup(
    repo = repository(),
    sha = branch_target(head(repository()))
    ),
  "data.frame"
  )
}
```

```{r UsefulInfo, results = "hold", include = is_draft, eval = is_draft, cache = FALSE}
print("Draft Information")
print("Working Directory")
print(getwd())
if (!is_null(git_info)) {
  print("GIT:")
  print(substr(x = git_info$sha, start = 0, stop = 6))
  print(git_info$summary)
  print(git_info$when)

}

```

```{r load_sample_data, include = !show_sql_code, eval = !use_live_sql}
if (file.exists(file.path("data", "data_processed_alpha_tiny.RDS"))){
  data_processed_alpha <- readRDS(file.path("data", "data_processed_alpha_tiny.RDS"))
} else {
    data_processed_alpha <- readRDS(file.path("data", "data_processed_alpha.RDS"))
}

if (file.exists(file.path("data", "data_processed_fafsa_tiny.RDS"))){
  data_processed_fafsa <- readRDS(file.path("data", "data_processed_fafsa_tiny.RDS"))
} else {
    data_processed_fafsa <- readRDS(file.path("data", "data_processed_fafsa.RDS"))
}
```

```{r Prepare_SQL_connection, include = show_sql_code, eval = TRUE}
if (use_live_sql) {
  dbcon <- odbc::dbConnect(
    drv = odbc::odbc(),
    driver = "SQL Server",
    server = project_sql_server,
    database = "CHEDW",
    trusted_connection = TRUE
    )
} else {
  dbcon <- dbConnect(RSQLite::SQLite(), ":memory:")
}
```

```{sql SQL_raw_ite_data, output.var = "raw_ite_data", include = show_sql_code, eval = use_live_sql, connection = dbcon}
SELECT
  s.CurrentCSN,
  ite.TermKey,
  ite.LocationKey,
  ite.ProgramMajorKey,
  ite.StudentFAStatusKey,
  ite.TransferCredit,
  ite.OtherAlternativeCredit,
  ite.UnderGradCreditEoT,
  ite.GradCreditEoT,
  ite.ProfPracticeCreditEoT,
  ite.UnderGradCreditCensus,
  ite.GradCreditCensus,
  ite.ProfPracticeCreditCensus,
  ite.DualCreditTotalCreditEoT
FROM CHEDW.dw.DimStudent AS s
INNER JOIN CHEDW.dw.FactInstTermEnrollment AS ite ON (ite.StudentKey = s.StudentKey)
```

```{r include = show_sql_code, eval = use_live_sql}
data_processed_alpha <- raw_ite_data %>%
  bind_cols(
    IndianaCHEmisc::split_termkey(.$TermKey)
  ) %>%
  select(-term_name, -termcode -fiscal_year, -TermKey) %>%
  mutate(term_n = 1) %>%
  mutate(term_season = readr::parse_factor(
    term_season,
    levels = c("Fall", "Spring", "Summer"
    ))) %>%
  group_by(CurrentCSN, academic_year, term_season, LocationKey, ProgramMajorKey, StudentFAStatusKey) %>%
  summarise_all(sum) %>%
  ungroup() %>%
  mutate(
    # is_undergrad = UnderGradCreditEoT >0 & DualCreditTotalCreditEoT == 0,
    # is_grad = GradCreditEoT >0,
    # is_prof_practice = ProfPracticeCreditEoT > 0,
    # is_dual_credit = DualCreditTotalCreditEoT > 0,
    # is_guest = (UnderGradCreditEoT + UnderGradCreditCensus == 0
    #             & GradCreditEoT + GradCreditCensus == 0
    #             & ProfPracticeCreditEoT + ProfPracticeCreditCensus == 0
    #             & DualCreditTotalCreditEoT == 0
    # ),
    #
    term_level = case_when(
      .$DualCreditTotalCreditEoT > 0 ~ "Dual Credit",
      (.$UnderGradCreditEoT > 0 | .$UnderGradCreditCensus > 0) & .$DualCreditTotalCreditEoT == 0 ~ "Undergrad",
      (.$GradCreditEoT > 0 | .$GradCreditCensus > 0) ~ "Graduate",
      (.$ProfPracticeCreditEoT > 0 | .$ProfPracticeCreditCensus > 0) ~ "Professional Practice",
      (.$UnderGradCreditEoT + .$UnderGradCreditCensus == 0
                & .$GradCreditEoT + .$GradCreditCensus == 0
                & .$ProfPracticeCreditEoT + .$ProfPracticeCreditCensus == 0
                & .$DualCreditTotalCreditEoT == 0
       ) ~ "Guest",
      TRUE ~ NA_character_
    ),
    is_drop = (
     (UnderGradCreditCensus > 0 & UnderGradCreditEoT == 0) |
     (GradCreditCensus > 0 & GradCreditEoT == 0) |
     (ProfPracticeCreditCensus > 0 & ProfPracticeCreditEoT == 0)
    ),
    has_incoming_credit = (OtherAlternativeCredit > 0) | (TransferCredit > 0)
    )
```

```{r define_save_function, include = FALSE}
rewrite_obj_rds <- function(object, dir = "data"){
  dir.create(path = dir, recursive = TRUE)
  file <- file.path(dir, paste0(substitute(object), ".RDS"))
  if (file.exists(file)) {file.remove(file)} #Delete Previous Version of the file
  saveRDS(object = object, file = file)
}
```

```{r save_sample_data_block, include = FALSE, eval = use_live_sql}
# This block is here to make my life easier so that when I am on my local machine, I can create an up to date set of sample data for Travis.
random_csn_vec <- sample(x = data_processed_alpha$CurrentCSN, size = 10000) # Pick 10000 students at random
data_processed_alpha_tiny <- data_processed_alpha %>% filter(CurrentCSN %in% random_csn_vec)

rewrite_obj_rds(data_processed_alpha_tiny)
remove(data_processed_alpha_tiny)
rewrite_obj_rds(data_processed_alpha)
```

```{r}
overlap <- data_processed_alpha %>%
  group_by(term_level, is_drop) %>%
  summarise(num = n())

datatable(overlap)
```
Here we can see that there all dual credit students are also counted as undergrad credits (which makes sense), but other types of credit are distinct.

```{r}
ordering_frame <- data_processed_alpha %>%
  unite(col = qx, academic_year, term_season) %>%
  arrange(CurrentCSN, qx) #%>%

  summarise(
    min = min(TermKey),
    max = max(TermKey),
    num = n()
    )

datatable(ordering_frame)
```

# FAFSA Information

Let's try loading in useful (self-reported) information from each student's FAFSA.

```{r Prepare_GRADS_SQL_connection, include = show_sql_code, eval = TRUE}
if (use_live_sql) {
  grads_con <- odbc::dbConnect(
    drv = odbc::odbc(),
    driver = "SQL Server",
    server = "IOTSQLP23vw\\P23vwiotPROD",
    database = "GRADS",
    trusted_connection = TRUE
    )
} else {
  grads_con <- dbConnect(RSQLite::SQLite(), ":memory:")
}
```
```{sql SQL_raw_GRADS_data, output.var = "raw_GRADS_data", include = show_sql_code, eval = use_live_sql, connection = grads_con}
SELECT
  in_AppId,
  ch_BusYear,
  ch_SSN AS DS01,
  ch_StuCitizenshipCd,
  ti_FirstBachDegreeFlg,
  ti_StuMaritalStatusCd,
  ti_StuBornBeforeFlg,
  ti_USVeteranFlg,
  ti_GradStuFlg,
  ti_StuMarriedFlg,
  ti_StuOthrDependFlg,
  ti_OrphanWardFlg,
  ti_InterestStuJobFlg,
  ti_InterestStuLoanFlg,
  ch_GEDEarned,
  ti_FthEduLevelCd,
  ti_MthEduLevelCd,
  ch_PellEligibilityFlg,
  ch_DependStatusCd -- Is dependent
FROM GRADS.dbo.Application
```

```{sql SQL_raw_psm_data, output.var = "raw_psm_data", include = show_sql_code, eval = use_live_sql, connection = dbcon}
SELECT DISTINCT
  DS01,
  CurrentCSN
FROM CHEDW.research.PostsecondaryMaster
```

```{r include = show_sql_code, eval = use_live_sql}
data_processed_fafsa <- raw_GRADS_data %>%
  inner_join(raw_psm_data, by = "DS01") %>%
  select(-DS01)

```

```{r save_sample_data_block_fafsa, include = FALSE, eval = use_live_sql}
# This block is here to make my life easier so that when I am on my local machine, I can create an up to date set of sample data for Travis.
random_csn_vec_fafsa <- c(random_csn_vec[1:9000], sample(x = data_processed_fafsa$CurrentCSN, size = 1000)) # Pick 9000 student overlap with alpha frame, and then 1000 students at random
data_processed_fafsa_tiny <- data_processed_fafsa %>% filter(CurrentCSN %in% random_csn_vec_fafsa)

rewrite_obj_rds(data_processed_fafsa_tiny)
remove(data_processed_fafsa_tiny)
rewrite_obj_rds(data_processed_fafsa)
```

```{r }
## Check that the frame exists
data_processed_fafsa %>%
  group_by(ch_PellEligibilityFlg, ch_GEDEarned) %>%
  summarise(num = n())
```
